cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/cosTheta1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/angle_cosTheta1.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/cosTheta2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/angle_cosTheta2.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/cosThetaStar.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/angle_cosThetaStar.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/helicityLD.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/angle_LD.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/phi1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/angle_phi1.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/phi.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/angle_phi.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/QGLikelihoodJet1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/data_QGLikelihoodJet1.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/QGLikelihoodJet2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/data_QGLikelihoodJet2.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/QGLikelihoodProd.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/data_loose_qg.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/deltaRjj.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/deltaRjj_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZee_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZee_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/mZjj_log.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZjj_log.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/mZjj.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZjj_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZll_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZll_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZmumu_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZmumu_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/mZZ_kinfit_hiMass_all.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/ZZInvMass_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_kinfit_hiMass_0btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZZ_kinfit_hiMass_data_0btag.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_kinfit_hiMass_1btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZZ_kinfit_hiMass_data_1btag.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_kinfit_hiMass_2btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZZ_kinfit_hiMass_data_2btag.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_kinfit_hiMass_gluetag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZZ_kinfit_hiMass_gluetag.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_kinfit_hiMass_sidebands_0btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZZ_kinfit_hiMass_sidebands_0btag.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_kinfit_hiMass_sidebands_1btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZZ_kinfit_hiMass_sidebands_1btag.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_kinfit_hiMass_sidebands_2btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZZ_kinfit_hiMass_sidebands_2btag.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/nEventsCategories_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/nEventsCategories_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/nEventsCategories_presel_log.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/nEventsCategories_presel_log.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/nJets_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/nJets_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/nvertex.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/nvertex.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_optLD_looseBTags_v2_PUHR11_73pb_ALL/nvertex_PUW.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/nvertex_PUW.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/ptJet1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/ptJet1_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/ptJet2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/ptJet2_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/ptLept1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/ptLept1_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/ptLept2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/ptLept2_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/ptZee.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/ptZee_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/ptZll.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/ptZll_presel.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/mZjj_0btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZjj_presel_0btag.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/mZjj_1btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZjj_presel_1btag.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/mZjj_2btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZjj_presel_2btag.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/mZjj_loMass.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZjj_presel_loMass.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/mZjj_medMass.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZjj_presel_medMass.eps
cp HZZlljjRMPlots_DATA_HR11_v2_madgraph_presel_PUHR11_73pb_ALL/mZjj_hiMass.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/mZjj_presel_hiMass.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/deltaRjj.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/tmva_deltaRjj.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/deltaRll_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/tmva_deltaRll.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/mZjj.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/tmva_massZjj.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/mZll_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/tmva_massZll.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/ptJet1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/tmva_ptJet1.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/ptJet2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/tmva_ptJet2.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/ptLept1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/tmva_ptLept1.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/ptLept2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/tmva_ptLept2.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/ptZll.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/tmva_ptZll.eps
cp FIT/HZZlljjRMPlots_DATA_HR11_v2_plusSignal_times3_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_0btag_withCurve.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/AllInOne_0btag_ll_LIMIT.eps
cp FIT/HZZlljjRMPlots_DATA_HR11_v2_plusSignal_times3_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_1btag_withCurve.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/AllInOne_1btag_ll_LIMIT.eps
cp FIT/HZZlljjRMPlots_DATA_HR11_v2_plusSignal_times3_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_2btag_withCurve.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/AllInOne_2btag_ll_LIMIT.eps
cp FIT/HZZlljjRMPlots_DATA_HR11_v2_plusSignal_times3_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_0btag_withCurve_log.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/AllInOne_0btag_ll_LIMIT_log.eps
cp FIT/HZZlljjRMPlots_DATA_HR11_v2_plusSignal_times3_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_1btag_withCurve_log.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/AllInOne_1btag_ll_LIMIT_log.eps
cp FIT/HZZlljjRMPlots_DATA_HR11_v2_plusSignal_times3_optLD_looseBTags_v2_PUHR11_73pb_ALL/mZZ_2btag_withCurve_log.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/AllInOne_2btag_ll_LIMIT_log.eps
cp FIT/EfficiencyFits_PUHR11_73pb/effFit_MU_0btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/effFit_MU_0btag.eps
cp FIT/EfficiencyFits_PUHR11_73pb/effFit_MU_1btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/effFit_MU_1btag.eps
cp FIT/EfficiencyFits_PUHR11_73pb/effFit_MU_2btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/effFit_MU_2btag.eps
cp FIT/EfficiencyFits_PUHR11_73pb/effFit_ELE_0btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/effFit_ELE_0btag.eps
cp FIT/EfficiencyFits_PUHR11_73pb/effFit_ELE_1btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/effFit_ELE_1btag.eps
cp FIT/EfficiencyFits_PUHR11_73pb/effFit_ELE_2btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/effFit_ELE_2btag.eps
cp FIT/upperLimit_HR11.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/provissima/plot_baysian.eps
