cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/cosTheta1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/angle_cosTheta1.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/cosTheta2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/angle_cosTheta2.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/cosThetaStar.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/angle_cosThetaStar.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/helicityLD.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/angle_LD.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/phi1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/angle_phi1.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/phi.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/angle_phi.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/QGLikelihoodJet1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/data_QGLikelihoodJet1.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/QGLikelihoodJet2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/data_QGLikelihoodJet2.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/QGLikelihoodProd.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/data_loose_qg.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/deltaRjj.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/deltaRjj_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/mZee_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZee_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/mZjj_log.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZjj_log.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/mZjj.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZjj_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/mZll_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZll_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/mZmumu_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZmumu_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/mZZ_kinfit_hiMass_all.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/ZZInvMass_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/mZZ_kinfit_hiMass_0btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZZ_kinfit_hiMass_data_0btag.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/mZZ_kinfit_hiMass_1btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZZ_kinfit_hiMass_data_1btag.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/mZZ_kinfit_hiMass_2btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZZ_kinfit_hiMass_data_2btag.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/mZZ_kinfit_hiMass_gluetag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZZ_kinfit_hiMass_gluetag.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/mZZ_kinfit_hiMass_sidebands_0btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZZ_kinfit_hiMass_sidebands_0btag.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/mZZ_kinfit_hiMass_sidebands_1btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZZ_kinfit_hiMass_sidebands_1btag.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/mZZ_kinfit_hiMass_sidebands_2btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZZ_kinfit_hiMass_sidebands_2btag.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/nEventsCategories_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/nEventsCategories_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/nEventsCategories_presel_log.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/nEventsCategories_presel_log.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/nJets_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/nJets_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/nvertex.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/nvertex.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_optLD_looseBTags_v2_ALL/nvertex_PUW.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/nvertex_PUW.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/ptJet1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/ptJet1_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/ptJet2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/ptJet2_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/ptLept1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/ptLept1_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/ptLept2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/ptLept2_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/ptZee.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/ptZee_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/ptZll.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/ptZll_presel.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/mZjj_0btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZjj_presel_0btag.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/mZjj_1btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZjj_presel_1btag.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/mZjj_2btag.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZjj_presel_2btag.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/mZjj_loMass.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZjj_presel_loMass.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/mZjj_medMass.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZjj_presel_medMass.eps
cp HZZlljjRMPlots_DATA_Run2011A_FULL_madgraph_presel_ALL/mZjj_hiMass.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/mZjj_presel_hiMass.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/deltaRjj.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/tmva_deltaRjj.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/deltaRll_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/tmva_deltaRll.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/mZjj.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/tmva_massZjj.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/mZll_presel.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/tmva_massZll.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/ptJet1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/tmva_ptJet1.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/ptJet2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/tmva_ptJet2.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/ptLept1.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/tmva_ptLept1.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/ptLept2.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/tmva_ptLept2.eps
cp HZZlljjRMPlots_MConly_madgraph_presel_ALL/ptZll.eps ~/scratch0/tdr2/notes/AN-11-388/trunk/plots/tmva_ptZll.eps
